"""alter column

Revision ID: 0401eff841f6
Revises: 9ef64d4fe7e8
Create Date: 2025-11-18 16:41:44.766677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0401eff841f6'
down_revision: Union[str, Sequence[str], None] = '9ef64d4fe7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clean_data', 'trans_count',
               existing_type=mysql.INTEGER(),
               type_=sa.BigInteger(),
               existing_comment='交易筆數',
               existing_nullable=False)
    op.alter_column('clean_data', 'trans_total',
               existing_type=mysql.BIGINT(),
               nullable=False,
               comment='交易金額')
    op.drop_column('clean_data', 'year_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clean_data', sa.Column('year_month', mysql.TEXT(), nullable=True))
    op.alter_column('clean_data', 'id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(),
               nullable=True,
               comment=None,
               existing_comment='ID主鍵',
               autoincrement=True)
    op.alter_column('clean_data', 'trans_total',
               existing_type=mysql.BIGINT(),
               nullable=True,
               comment=None,
               existing_comment='交易金額')
    op.alter_column('clean_data', 'trans_count',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(),
               existing_comment='交易筆數',
               existing_nullable=False)
    # ### end Alembic commands ###
