"""add TABLE clean_data

Revision ID: 7449021256ba
Revises: b89529abb553
Create Date: 2025-12-04 16:24:25.699021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7449021256ba'
down_revision: Union[str, Sequence[str], None] = 'b89529abb553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clean_data',
    sa.Column('ym', sa.String(length=20), nullable=False, comment='年月'),
    sa.Column('nation', sa.String(length=20), nullable=False, comment='地區'),
    sa.Column('industry', sa.String(length=20), nullable=False, comment='產業別'),
    sa.Column('age_level', sa.String(length=20), nullable=False, comment='年齡層'),
    sa.Column('trans_count', sa.BigInteger(), nullable=False, comment='交易筆數'),
    sa.Column('trans_total', sa.BigInteger(), nullable=False, comment='交易金額'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID主鍵'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clean_data')
    # ### end Alembic commands ###
