"""add column-points_json

Revision ID: 581bd5743c27
Revises: 0401eff841f6
Create Date: 2025-11-27 16:38:09.801446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '581bd5743c27'
down_revision: Union[str, Sequence[str], None] = '0401eff841f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chart_requests', sa.Column('points_json', sa.JSON(), nullable=False, comment='圖表指標'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_requests', 'points_json')
    # ### end Alembic commands ###
