"""alter Column-points_json

Revision ID: 989f18086f02
Revises: 581bd5743c27
Create Date: 2025-11-28 11:59:52.783851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '989f18086f02'
down_revision: Union[str, Sequence[str], None] = '581bd5743c27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart_requests', 'points_json',
               existing_type=mysql.JSON(),
               nullable=True,
               existing_comment='圖表指標')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chart_requests', 'points_json',
               existing_type=mysql.JSON(),
               nullable=False,
               existing_comment='圖表指標')
    # ### end Alembic commands ###
