"""init tables

Revision ID: 9ef64d4fe7e8
Revises: 
Create Date: 2025-11-13 10:07:53.891981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef64d4fe7e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_results',
    sa.Column('chart_type', sa.String(length=50), nullable=False, comment='圖形類別'),
    sa.Column('params_json', sa.JSON(), nullable=False, comment='參數'),
    sa.Column('params_figure', sa.JSON(), nullable=False, comment='圖表大項'),
    sa.Column('cache_key', sa.String(length=100), nullable=False, comment='唯一索引'),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'FAILED', name='result_status_enum'), nullable=False, comment='產製狀態'),
    sa.Column('file_path', sa.String(length=100), nullable=True, comment='圖檔路徑'),
    sa.Column('create_by', sa.Integer(), nullable=True, comment='建立者ID'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='建立時間'),
    sa.Column('update_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新時間'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID主鍵'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_results_cache_key'), 'chart_results', ['cache_key'], unique=True)
    op.create_table('clean_data',
    sa.Column('year_month', sa.String(length=20), nullable=False, comment='年月'),
    sa.Column('nation', sa.String(length=20), nullable=False, comment='地區'),
    sa.Column('industry', sa.String(length=20), nullable=False, comment='產業別'),
    sa.Column('age_level', sa.String(length=20), nullable=False, comment='年齡層'),
    sa.Column('trans_count', sa.Integer(), nullable=False, comment='交易筆數'),
    sa.Column('trans_total', sa.Integer(), nullable=False, comment='交易金額'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID主鍵'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chart_requests',
    sa.Column('chart_type', sa.String(length=50), nullable=False, comment='圖形類別'),
    sa.Column('params_json', sa.JSON(), nullable=False, comment='參數'),
    sa.Column('cache_hit', sa.Boolean(), nullable=False, comment='是否命中快取'),
    sa.Column('result_id', sa.Integer(), nullable=True, comment='結果ID'),
    sa.Column('create_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='查詢時間'),
    sa.Column('id', sa.Integer(), nullable=False, comment='ID主鍵'),
    sa.ForeignKeyConstraint(['result_id'], ['chart_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_requests')
    op.drop_table('clean_data')
    op.drop_index(op.f('ix_chart_results_cache_key'), table_name='chart_results')
    op.drop_table('chart_results')
    # ### end Alembic commands ###
