"""alter table

Revision ID: b89529abb553
Revises: 989f18086f02
Create Date: 2025-11-28 14:55:31.415532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b89529abb553'
down_revision: Union[str, Sequence[str], None] = '989f18086f02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_requests', 'points_json')
    op.add_column('chart_results', sa.Column('points_json', sa.JSON(), nullable=True, comment='圖表指標'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chart_results', 'points_json')
    op.add_column('chart_requests', sa.Column('points_json', mysql.JSON(), nullable=True, comment='圖表指標'))
    # ### end Alembic commands ###
